###
GET http://localhost:3001/api/product
###
POST http://localhost:3001/api/product
Content-Type: application/json

{
    "nombre": "TEST Mario KART",
    "stock": 23,
    "categoria": ["test", "Minijuegos"],
    "precio" : 24.99,
    "estudio": "Nintendo",
    "lanzamiento": "2005-11-24",
    "pegi": 7,
    "plataforma": ["wii", "wii U"],
    "img":  "https://m.media-amazon.com/images/I/71usPUo4uWL._AC_SX425_.jpg"
}

###
DELETE http://localhost:3001/api/product
###
GET http://localhost:3001/api/product/6238f2920155e80f9e60b38c
###
POST http://localhost:3001/api/product/6238f1f00155e80f9e60b37f
Content-Type: application/json

{
    "nombre": "33 Mario KART",
    "stock": 23,
    "categoria": ["Multijugador", "Minijuegos"],
    "precio" : 24.99,
    "estudio": "Nintendo",
    "lanzamiento": "2005-11-24",
    "pegi": 7,
    "plataforma": ["wii", "wii U"],
    "img":  "https://m.media-amazon.com/images/I/71usPUo4uWL._AC_SX425_.jpg"
}
###
DELETE http://localhost:3001/api/product/62373b16aebd116d866a186f

###
GET http://localhost:3001/api/category/test
###