###
GET http://localhost:3003/api/status

###
GET http://localhost:3003/api/user

###
POST http://localhost:3003/api/user
Content-Type: application/json

{
    "rol": "Administrador"
}
###
POST http://localhost:3003/api/user
Content-Type: application/json

{
    "rol": "Cliente",
    "username": "Coco"
}

###
DELETE http://localhost:3003/api/user

###
DELETE http://localhost:3003/api/user/626bf1645826c0ed61d506f
###
GET http://localhost:3003/api/user/626bf164582c0ede61d506f
