###
GET http://localhost:3003/api/status

###
GET http://localhost:3003/api/user

###
POST http://localhost:3003/api/user
Content-Type: application/json

{
    "rol": "Cliente",
    "username": "Coco"
}
###
POST http://localhost:3003/api/user
Content-Type: application/json

{
    "rol": "Administrador",
    "username": "Mango"
}

###
DELETE http://localhost:3003/api/user

###
DELETE http://localhost:3003/api/user/626bf1575826c0ede61d506b
###
GET http://localhost:3003/api/user/626bf1575826c0ede61d506b
