###
GET http://localhost:3002/api/products

###
GET http://localhost:3002/api/status

###
POST http://localhost:3002/api/order
Content-Type: application/json

{
    "id_producto": "A",
    "id_usuario": "A",
    "cantidad": 3,
    "comprador": "A",
    "direccion": "A"
}
###
GET http://localhost:3002/api/order
###
DELETE http://localhost:3003/api/user

###
DELETE http://localhost:3002/api/order/626c005a7a5424d775c06aa2
Auth: 626bf1645826c0ede61d506d
Content-Type: application/json

{
    "auth": "626bf1645826c0ede61d506d"
}
###
GET http://localhost:3003/api/user/626ba7ea2a7fc04f5067b9c4
